# Generated by Django 5.2.10 on 2026-03-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='used', max_length=20),
        ),
    ]
