# Generated by Django 5.2.10 on 2026-03-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionitem_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
