from django.urls import path
from .views import (
    AuctionList,
    AuctionDetail,
    PlaceBid,
    UserDashboard,
    RegisterUserView,
    CustomLoginView,
    WatchListToggle,
    WatchlistList,
    NotificationList,
    MarkNotificationRead,
    DeleteNotification,
    ClearAllNotifications,
    CreateStripeCheckoutSession,
    EndAuctionEarly,
    MarkAuctionPaid,
    AuctionHomeSections,UserProfileView,
    SupportTicketListCreateView,
    SupportTicketDetailView,
    TicketResponseCreateView,
)

urlpatterns = [
    path("auctions/", AuctionList.as_view(), name="auction-list"),
    path("auctions/<int:pk>/", AuctionDetail.as_view(), name="auction-detail"),
    path("auctions/<int:pk>/bid/", PlaceBid.as_view(), name="place-bid"),
    path("dashboard/", UserDashboard.as_view(), name="user-dashboard"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("register/", RegisterUserView.as_view(), name="register"),
    path(
        "auctions/<int:pk>/watchlist/",
        WatchListToggle.as_view(),
        name="watchlist-toggle",
    ),
    path("watchlist/", WatchlistList.as_view(), name="watchlist-list"),
    path("notifications/", NotificationList.as_view(), name="notifications"),
    path(
        "notifications/<int:pk>/read/",
        MarkNotificationRead.as_view(),
        name="notification-read",
    ),
    path("profile/", UserProfileView.as_view(), name="user-profile"),
    path("notifications/<int:pk>/delete/", DeleteNotification.as_view()),
    path("notifications/clear-all/", ClearAllNotifications.as_view()),
    path("create-payment-intent/", CreateStripeCheckoutSession.as_view()),
    path("auctions/<int:pk>/end/", EndAuctionEarly.as_view(), name="end-auction-early"),
    path("auctions/<int:pk>/mark-paid/", MarkAuctionPaid.as_view(), name="mark-paid"),
    path("home-sections/", AuctionHomeSections.as_view(), name="home-sections"),
    path("support/tickets/", SupportTicketListCreateView.as_view(), name="ticket-list"),
    path("support/tickets/<int:pk>/", SupportTicketDetailView.as_view(), name="ticket-detail"),
    path("support/tickets/<int:pk>/reply/", TicketResponseCreateView.as_view(), name="ticket-reply"),
]
